[[headers]]
  for = "/*"
  [headers.values]
  # --- Security & privacy ---
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'nonce-ABC123' www.googletagmanager.com www.google-analytics.com;
    connect-src 'self' www.google-analytics.com region1.google-analytics.com;
    img-src 'self' data: blob: www.google-analytics.com www.googletagmanager.com;
    style-src 'self' 'unsafe-inline' fonts.googleapis.com;
    font-src 'self' data: fonts.gstatic.com;
    frame-src www.googletagmanager.com;
    object-src 'none';
    base-uri 'self';
    frame-ancestors 'none';
    form-action 'self';
    upgrade-insecure-requests;
  """
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Resource-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# (Optional) Better caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
